table Orders
	lineageTag: 1828a23b-e3ca-4e8b-ba77-c1e9ae1b6d28

	column 'Order ID'
		dataType: string
		lineageTag: 29e01379-389c-4074-8b32-9eebbab5601b
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 203cd6c4-56bb-4c36-b5aa-949e6ee0f03a
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1cffa3c0-d422-4d25-9c19-ede238091fda
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: baffe4c0-2eab-444f-bd91-c272dd96ae97
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: e6707c46-d255-4be8-99e3-91d532070465
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: d515606e-b90f-43c7-9dcc-b7553d46b774
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: d41a66a9-0701-4d53-acf6-523928e3863c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 1a29c722-b362-4a49-84cd-02a15bfa87ab
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 478abf31-68de-4923-a279-4e2ba7f6b822
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 27baaba4-0866-4000-a3ac-c83dcdd85216
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: bcc95c67-d904-4f54-bc00-21e994c49a2c
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 07c33eed-74ae-4f92-ac2b-d96422220b66
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: b1b59bc2-1019-4b4b-928f-5e688067c91e
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 850c5f26-8077-4965-9ce2-d0102932df9f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 74f34e0b-e4dc-4683-9db0-ad638edd23e1
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: acc8b6b4-499b-44bf-8d9f-6b8c355e068b
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 49541f99-809c-496f-8621-10183fc63f33
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: double
		lineageTag: 9e67658a-ea79-4aee-9f2e-82a8177bdebd
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		lineageTag: 335cb883-fe5c-4972-b9b9-c4044a55d08a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 4fe412fb-52b9-421c-8479-a174bf5deba6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping Cost'
		dataType: double
		lineageTag: 234ed284-29b7-43ca-bcf5-bb4eb9f1fcf6
		summarizeBy: sum
		sourceColumn: Shipping Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Priority'
		dataType: string
		lineageTag: a497f0b6-48f7-4fd4-b596-caa4838ee5a5
		summarizeBy: none
		sourceColumn: Order Priority

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 36ff328a-7212-485c-84d1-05f20b7e5d2e
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\navee\Documents\Global Superstore Data.xlsx"), null, true),
				    Global_Superstore2_Sheet = Source{[Item="Global_Superstore2",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Global_Superstore2_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order Date", type date}, {"Ship Date", type date}, {"Customer Name", type text}, {"Segment", type text}, {"City", type text}, {"State", type text}, {"Ship Mode", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", type number}, {"Discount", type number}, {"Profit", type number}, {"Shipping Cost", type number}, {"Order Priority", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

